// Upstream: RandomProgramGenerator.cpp (CLI helpers: version/help/arg parse).
// Pin: pkgs.csmith git 0cdc710315cfee9035e22ef4363ca479270d1934.
package csmith

import (
	"fmt"
	"strconv"
	"strings"
)

// PackageString mirrors PACKAGE_STRING for version output.
// Upstream self-reports csmith 2.4.0; fair rewrite identifies go-csmith.
const PackageString = "go-csmith (fair rewrite)"

// GitVersion mirrors git_version string in print_version.
const GitVersion = "fair-rewrite"

// PrintVersion mirrors RandomProgramGenerator::print_version.
// RandomProgramGenerator.cpp:119–124.
func PrintVersion() string {
	return PackageString + "\nGit version: " + GitVersion + "\n"
}

// ParseStringArg mirrors parse_string_arg.
// RandomProgramGenerator.cpp:127–130 — non-empty and not starting with "--".
func ParseStringArg(arg string) (string, bool) {
	if arg == "" {
		return "", false
	}
	if strings.HasPrefix(arg, "--") {
		return "", false
	}
	return arg, true
}

// ParseIntArg mirrors parse_int_arg.
// RandomProgramGenerator.cpp:132–142 — sscanf %lu style; fail on non-integer.
func ParseIntArg(arg string) (uint64, bool) {
	// C++ sscanf stops at non-digit; Go ParseUint is stricter on full string.
	// Allow optional whitespace.
	arg = strings.TrimSpace(arg)
	if arg == "" {
		return 0, false
	}
	// match unsigned long parse; reject negative/sign prefix
	if arg[0] == '-' || arg[0] == '+' {
		return 0, false
	}
	v, err := strconv.ParseUint(arg, 10, 64)
	if err != nil {
		return 0, false
	}
	return v, true
}

// ArgCheck mirrors arg_check — i must be < argc.
// RandomProgramGenerator.cpp:690–696.
// Returns error message when missing; empty string when ok.
func ArgCheck(argc, i int) string {
	if i >= argc {
		return fmt.Sprintf("expect arg at pos %d", i)
	}
	return ""
}

// PrintHelp mirrors print_help common options (fair subset).
// RandomProgramGenerator.cpp:143+ — most common flags only.
func PrintHelp() string {
	var b strings.Builder
	b.WriteString("Command line options: \n\n")
	b.WriteString("  --help or -h: print this information.\n\n")
	b.WriteString("  -hh: describe extra options probably useful only for Csmith developers.\n\n")
	b.WriteString("  --version or -v: print the version of Csmith.\n\n")
	b.WriteString("  --seed <seed> or -s <seed>: use <seed> instead of a random seed generated by Csmith.\n\n")
	b.WriteString("  --output <filename> or -o <filename>: specify the output file name.\n\n")
	return b.String()
}

// PrintAdvancedHelp mirrors print_advanced_help (developer options stub).
// Full upstream list is large; fair rewrite points to --help and SPEC.
func PrintAdvancedHelp() string {
	return "Advanced options: see go-csmith --help and SPEC.md for the fair-rewrite surface.\n" +
		"Non-default extensions (--klee, --crest, --coverage-test) are implemented when enabled.\n"
}
