name: autorelease
on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
  workflow_dispatch:

jobs:
  autorelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
      - run: mise run install
      - run: mise run codegen
      - name: Check for changes
        id: git-check
        run: |
          git add -A && git diff --staged --exit-code || echo "changes=true" >> $GITHUB_OUTPUT
      - name: Create PR if differences exist
        if: steps.git-check.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          title: "chore: update generated code"
          body: "This PR updates generated code via `mise run codegen`."
          branch: "chore/update-codegen"
          commit-message: "chore: update generated code"
      - run: mise run ci
      - name: Release
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release create ${{ github.ref_name }} --generate-notes
      - name: Upload Artifacts
        if: github.event_name == 'workflow_dispatch' || startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: artifacts
          path: ./*
